version: "3.7"
services:
  syncthing:
    build: ./syncthing
    networks:
    - syncthing
    volumes:
      - type: bind
        source: /home/vagrant/syncthing
        target: /opt/syncthing
    restart: always

  squid:
    build: ./squid
    networks:
    - syncthing
    ports:
    - 443:8443
    restart: always
  
networks:
  syncthing:  
    
