- name: Test for /var/log/ansible_docker attempted
  command: 'test -e /var/log/ansible_docker'
  register: ansible_docker
  ignore_errors: True

- name: Install docker dependencies 
  when: ansible_docker is failed
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common

- name: Add an Apt signing key, uses whichever key is at the URL
  when: ansible_docker is failed
  apt_key:
    id:  9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name:  Add specified repository into sources list.
  when: ansible_docker is failed
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/debian buster stable'
    state: present

- name: Apt-get update after adding Docker Repo
  when: ansible_docker is failed
  apt:
    update_cache: yes

- name: Install docker
  when: ansible_docker is failed
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Add vagrant user to docker group
  when: ansible_docker is failed
  user:
    name: vagrant
    group: docker
    
- name: Touch /var/log/ansible_docker
  ignore_errors: True
  file:
    path: /var/log/ansible_docker
    state: touch
    
